"""empty message

Revision ID: 81db2f33b0d3
Revises: 8d198ce1ad48
Create Date: 2023-08-28 11:39:22.081278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81db2f33b0d3'
down_revision = '8d198ce1ad48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
