"""yay?

Revision ID: 87abb9510584
Revises: 5b4fe7f89d0f
Create Date: 2023-08-22 17:25:26.410856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87abb9510584'
down_revision = '5b4fe7f89d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squishes'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('user_squishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squish_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['squish_id'], ['squishes.id'], name=op.f('fk_user_squishes_squish_id_squishes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_squishes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_squishes'))
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_user'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    op.drop_table('user_squishes')
    op.drop_table('users')
    op.drop_table('squishes')
    # ### end Alembic commands ###
